### ISSUE TITLE
error in readGeneric when reading files with numeric chromosomes

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/genomation#133]
Ensembl uses chromosomes without the chr prefix - e.g. 1,2,3 and read generic
parses that as integer, and breaks when it finds chromosome X.

It should put the column which is designated as chromosome to be always of type character

**Comment by al2na** [comment]
is this still an issue with the readr?

**Comment by katwre** [comment]
it's not an issue with readr. It's because we check classes of columns by looking at first 30 rows. So when there are `numeric` chromosomes in first 30 rows and in 31st row is "X" chromosome then it breaks. Putting the column which is designated as chromosome to be always a character could be a good idea then.

**Comment by al2na** [comment]
@katwre we should fix this in the next release as well.
