### ISSUE TITLE
problems concerning results produced by "annotateWithGeneParts" function

### ISSUE THREAD

**Issue by frylhc** [BIMSBbioinfo/genomation#199]
Hi Dr. Akalin, I am using genomation package to annotate DMSs and DMRs I got from my methylation data. After executing the "annotateWithGeneParts" function, the package produced "diffAnnoDMS" file, then I took a further closer look at the file, it produces the following lines:
 `> diffAnnoDMS
Summary of target set annotation with genic parts
Rows in target set: 1887
-----------------------
percentage of target features overlapping with annotation:
  promoter       exon     intron intergenic 
     29.41      47.01      43.88       5.51 

percentage of target features overlapping with annotation:
(with promoter > exon > intron precedence):
  promoter       exon     intron intergenic 
     29.41      28.83      36.25       5.51 

percentage of annotation boundaries with feature overlap:
promoter     exon   intron 
    2.69     0.52     0.57 

summary of distances to the nearest TSS:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      6     825    2246    3664    4576   44905 
`
I am a bit confusing here, I saw "percentage of target features overlapping with annotation:" twice, but are followed by different results, do the two lines mean differently?

**Comment by katwre** [comment]
Hi @frylhc,
In the first line, it's written "percentage of target features overlapping with annotation" and in the second  "percentage of target features overlapping with annotation: (with promoter > exon > intron precedence):". So then, the second "percentage of target features overlapping with annotation:" differs from the first one because it assumes that the promoters will be treated as the most important, and exons as the second most important, and so on. Such that, if an interval overlaps with features are part of promoters, the rest of its overlaps with other elements in the annotation that are exons and introns will be ignored.
Hope it helps,
Kasia

**Comment by frylhc** [comment]
I understand. That helps a lot. Thank you so much.
