### ISSUE TITLE
as.matrix() should coerce scoreMatrix to a R matrix

### ISSUE THREAD

**Issue by al2na** [BIMSBbioinfo/genomation#60]

**Comment by ATpoint** [comment]
@al2na Referring to this question, I would like to sort the scoreMatrix by row. Given a scoreMatrix that stores the intensity signals in a range of -2000 to +2000 of a peak center, I would like to sort the rows decreasingly by signal at the peak center. This is trivial if I transfer scoreMatrix@.Data to a R matrix, but I cannot manage it with this scoreMatrix object or rather transform the R matrix back into the scoreMatrix object. Any suggestions would be appreciated.

**Comment by katwre** [comment]
Hi Alexander,

To convert matrix to score matrix "as" function works for me:

as(your_matrix, "ScoreMatrix")

Cheers,
Katarzyna

On Sep 23, 2016 6:37 PM, "Alexander Toenges" <notifications@github.com>
wrote:

@al2na <https://github.com/al2na> Referring to this question, I would like
to sort the scoreMatrix by row. Given a scoreMatrix that stores the
intensity signals in a range of -2000 to +2000 of a peak center, I would
like to sort the rows decreasingly by signal at the peak center. This is
trivial if I transfer scoreMatrix@.Data to a R matrix, but I cannot manage
it with this scoreMatrix object or rather transform the R matrix back into
the scoreMatrix object. Any suggestions would be appreciated.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BIMSBbioinfo/genomation/issues/60#issuecomment-249241077>,
or mute the thread

**Comment by ATpoint** [comment]
Works great, thanks a lot!
